config/routes.rb
Rails.application.routes.draw do

  root 'archives#index'

  get 'index' => 'archives#index'

  namespace :admin do
    resources :articles do
      resources :comments, only: [:create, :destroy]
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    root 'sessions#new'
  end

  resources :archives, only: [:index, :show] do
    resources :comments, only: [:create]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true, length: { maximum: 64 }
  validates :content, presence: true, length: { maximum: 65535 }
end

app/models/comment.rb
class EmailValidator < ActiveModel::EachValidator
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value.nil? || value.empty? || value =~ VALID_EMAIL_REGEX
  end
end

class Comment < ActiveRecord::Base
  belongs_to :article

  # desc sort by created_at
  default_scope -> { order(created_at: :desc) }

  validates :article_id, presence: true
  validates :commenter, presence: true, length: {maximum: 255}
  validates :content, presence: true, length: {maximum: 65535}
  validates :email, length: {maximum: 255}, email: true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate!

  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = "Blog create success!"
      redirect_to [:admin, @article]
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Blog update success!"
      redirect_to [:admin, @article]
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash[:success] = "Blog delete success!"
    redirect_to admin_articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    if @comment.save
      flash[:success] = "评论博客成功!"
    redirect_to admin_article_path(@article)
    else
      @comments = @article.comments
      render 'admin/articles/show'
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    flash[:success] = "删除评论成功!"
    @comment.destroy
    redirect_to admin_article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :email, :content)
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
    if is_logged?
      redirect_to admin_articles_path
    end
  end

  def create
    if log_in(session_params)
      flash[:success] = "Welcome to the XBlog, my master!"
      redirect_to admin_articles_path
    else
      flash.now[:warning] = "用户名或密码错误!"
      render 'new'
    end
  end

  def destroy
    log_out if is_logged?
    redirect_to new_admin_session_path
  end

  private
  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :format_time

  include ApplicationHelper
  include Admin::SessionsHelper

  def format_time(time)
    time.localtime.strftime("%Y-%m-%d %H:%M")
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:archive_id])
    @comment = @article.comments.build(comment_params)
    if @comment.save
      flash[:success] = "评论成功!"
      redirect_to archive_path(@article)
    else
      @comments = @article.comments
      flash.now[:warning] = "评论失败!"
      render 'archives/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :email, :content)
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
  def authenticate!
    if ! session[:admin]
      flash[:error] = '请先登录后台管理!'
      cookies[:urlback] = request.original_url
      redirect_to new_admin_session_path
    end
  end

  def log_in(params)
    if session[:admin] != true
      digest = Digest::SHA1.hexdigest(params[:password])
      if ENV['XBLOG_USERNAME'].blank?
        session[:admin] = false
      elsif params[:username] != ENV['XBLOG_USERNAME']
        session[:admin] = false
      elsif digest != ENV['XBLOG_PASSWORD']
        session[:admin] = false
      else
        session[:admin] = true
      end
    end
    session[:admin]
  end

  def log_out()
    session.delete(:admin)
  end

  def is_logged?
    session[:admin] == true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      :autolink => true,
      :space_after_headers => true,
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :hard_wrap => true,
      :strikethrough =>true
    }
    markdown = Redcarpet::Markdown.new(HTMLwithCodeRay,options)
    markdown.render(h(text)).html_safe
  end

  class HTMLwithCodeRay < Redcarpet::Render::HTML
    SyntaxMatcher = [
      {
        :matcher => [
          /(char[\s]+\w+?;)|(short[\s]+\w+?;)|(int[\s]+\w+?;)|(long[\s]+\w+?;)|(float[\s]+\w+?;)|(double[\s]+\w+?;)/,
          /for[\s]+\([\s\S]*?\)/,
          /[\w]+?[\s]+[\w]+?[\s]*\([\s\S]*?\)[\s]+{/,
          /struct[\s\S]*?{/,
          /class[\s\S]*?{/,
        ],
        :format => :cplusplus
      },
      {
        :matcher => [
          /local[\s]+[\w]+?/,
          /for[\s][\w]+?[\s]+in[\s]+[i]?pairs/,
          /local[\s]+function/,
          /function[\s]+?[\w]+/,
        ],
        :format => :lua
      },
      {
        :matcher => [
          /def[\s]+[\w]+[\s\S]+?end/,
          /class[\s]+[\w]+[\s\S]+?end/,
          /module[\s]+[\w]+[\s\S]+?end/,
        ],
        :format => :ruby
      },
      {
        :matcher => [
          /for[\s][\w]+?[\s]+in[\s]+[\w]+?[\s]*:/,
          /def[\s]+[\w]+[\s]*:/,
          /class[\s]+[\w]+[\s]*:/,
        ],
        :format => :python
      },
    ]

    def code_type(text)
      HTMLwithCodeRay::SyntaxMatcher.each do |o|
        o[:matcher].each do |m|
          return o[:format] if m =~ text
        end
      end
      return :text
    end

    def block_code(code, language)
      language ||= code_type(code)
      CodeRay.scan(code, language).div(:tab_width=>2, :line_numbers => nil)
    end
  end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/articles/_article.html.erb
<% if defined?(simple) && simple %>
<div class="sep">
  <h3><%= link_to article.title, admin_article_path(article), class: "archive-title" %></h3>
  <p>
    <div class="archive-label" align="right">
      <span class="glyphicon glyphicon-calendar"></span>
      <%= format_time(article.created_at) %>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <span class="glyphicon glyphicon-comment"></span>
      <%= article.comments.size %>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <span class="glyphicon glyphicon-edit"></span>
      <%= link_to 'Edit', edit_admin_article_path(article) %>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <span class="glyphicon glyphicon-trash"></span>
      <%= link_to 'Destroy', admin_article_path(article),
      method: :delete, data: { confirm: '确定要删除这篇博客吗?' } %>
    </div>
  </p>
</div>
<% else %>

<div class="article-title">
  <h1 align="center"><%= article.title %></h1><br>
</div>
<div class="article-content">
  <%= markdown(article.content) %>
  <br><br><br><br>
  <div class="text-info">
    <p align="right">
      发布时间: <%= format_time(article.created_at) %>&nbsp;&nbsp;&nbsp;&nbsp;
      最后编辑: <%= format_time(article.updated_at) %>
    </p>
    <div align="right">
      <%= link_to '编辑博客', edit_admin_article_path(@article) %> |
    </div>
  </div>
</div>

<% end %>

app/views/admin/articles/_form.html.erb
<%= form_for([:admin, @article]) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.submit (defined?(text) ? text : nil) %>
</p>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', text: "update article" %>

<%= link_to 'Back', admin_article_path(@article) %>

app/views/admin/articles/index.html.erb
<div class="text-left" id="index">
  <div class="text-center create-article">
    <a href="<%= new_admin_article_path %>" >
      <input name="commit" value="创建新博客！" class="btn btn-large btn-primary" id="commit" type="button">
    </a>
  </div>
  <%= render @articles, simple: true %>

</div>

<div align="right">
  <%= link_to '退出登录', admin_session_path(1), method: :delete, data: { confirm: 'Are you sure?' } %>
  <span class="glyphicon glyphicon-log-out"></span>
</div>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', text: "create article" %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<%= render @article %>

<!-- <%= render 'admin/comments/form' %> -->
<%= render @comments %>

<div align="right">
<%= link_to '退后', admin_articles_path %>
</div>

app/views/admin/comments/_comment.html.erb
<% if comment.valid? %>
<div class="comment">
  <div class="comment-content">
    <p><%= comment.content.html_safe %></p>
  </div>
  <div class="text-info text-right">
    <div class="comment-info">
      <small>
        <%= format_time(comment.created_at) %>
        by
        <%= comment.commenter %>
      </small>
    </div>
    <% if not comment.email.empty? %>
    <div class="comment-email">
      <p>联系我: <a href="mailto:#"><%=comment.email%></a></p>
    </div>
    <% end %>
    <%= link_to '删除评论', admin_article_comment_path(@article, comment), method: :delete,
    data: { confirm: '确定要删除评论?' } %>
  </div>
</div>
<% end %>

app/views/admin/comments/_form.html.erb
<% object = (defined?(@comment) ? @comment : @article.comments.build) %>

<%= form_for([:admin, @article, object]) do |f| %>
  <%= render 'shared/error_messages', object: object %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit defined?(text)? text : "comment it!" %>
  </p>
<% end %>

app/views/archives/_article.html.erb
<% if defined?(simple) && simple %>
<p><%= link_to article.title, archive_path(article) %> --- <%= article.content[0,20] %></p>
<% else %>
<div class="article-title">
  <h1 align="center"><%= article.title %></h1><br>
</div>
<div class="article-content">
  <%= markdown(article.content) %>
  <br><br><br><br>
<div class="text-info">
<p align="right">
  发布时间: <%= format_time(article.created_at) %>&nbsp;&nbsp;&nbsp;&nbsp;
  最后编辑: <%= format_time(article.updated_at) %>
</p>
</div>
</div>
<% end %>

app/views/archives/index.html.erb
<div class="text-left" id="index">

  <ul class="table table-hover archives-field">
    <% @articles.each do |article| %>
    <li>
      <h3><%= link_to article.title, archive_path(article), class: "archive-title" %></h3>
      <p>
        <div class="archive-label" align="right">
          <span class="glyphicon glyphicon-calendar"></span>
          <%= format_time(article.created_at) %>
          &nbsp;&nbsp;&nbsp;&nbsp;
          <span class="glyphicon glyphicon-comment"></span>
          <%= article.comments.size %>
        </div>
      </p>
    </li>
    <% end %>
  </ul>

  <div align="center">
    <%= will_paginate @articles %>
  </div>
</div>

app/views/archives/show.html.erb
<div class="text-left">
  <div class="content">
    <%= render 'archives/article', article: @article %>

    <%= render 'comments/form' %><br><br>
    <%= render @comments %>
  </div>

  <div class="text-right">
    <br><br><%= link_to '后退', archives_path %>
    <span class="glyphicon glyphicon-home"></span>
  </div>
</div>

app/views/articles/_article.html.erb
<% if defined?(simple) && simple %>
<table>
  <tr>
    <td><%= link_to article.title, article_path(article) %> --- <%= article.content[0,20] %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</table>
<% else %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p> publish at: <%= format_time(@article.created_at) %> </p>
<p> last edit at: <%= format_time(@article.updated_at) %> </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'Back', article_path(@article) %>

app/views/articles/index.html.erb
<h1>Articles List</h1>

<%= render @articles, simple: true %>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.submit "create article" %>
</p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2>Article:</h2>
<%= render @article %>

<h2>Comments:</h2>
<%= render @comments %>

<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "comment it!" %>
  </p>
<% end %>

<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<% if comment.valid? %>

<div class="comment">
  <div class="comment-content">
    <p><%= comment.content.html_safe %></p>
  </div>
  <div class="text-info text-right">
    <div class="comment-info">
      <small>
        <%= format_time(comment.created_at) %>
        by
        <%= comment.commenter %>
      </small>
    </div>
    <% if not comment.email.empty? %>
    <div class="comment-email">
      <p>联系我: <a href="mailto:#"><%=comment.email%></a></p>
    </div>
    <% end %>
  </div>
</div>

<% end %>

app/views/comments/_form.html.erb
<% object = (defined?(@comment) ? @comment : @article.comments.build) %>

<div id="add-comment">
<%= form_for object, url: archive_comments_path(@article),
    html: {onsubmit: "return validate_form(this);"} do |f| %>
  <%= render 'shared/error_messages', object: object %>

  <p><%= f.text_field :commenter, placeholder: "昵称", id: "commenter"  %></p>
  <p><%= f.text_field :email, placeholder: "邮箱", id: "email" %></p>
  <p><%= f.text_area :content, placeholder: "发表你的评论...", rows: 5, id: "content" %></p>
  <p><%= f.submit (defined?(text)? text : "评论"), class: "btn btn-large btn-primary",
  id: "commit" %></p>
<% end %>
<br>
</div>

<script>
function validate_name(field, defaultText) {
  with (field) {
    if(value.length <= 0) {
      alert("昵称不能为空！");
      return false;
    }
    else if(value.length > 64) {
      alert("昵称过长！");
      return false;
    }
  }
  return true;
}

function validate_email(field, defaultText) {
  with (field) {
    if(value.length <= 0) return true;
    apos=value.indexOf("@")
    dotpos=value.lastIndexOf(".")
    if (apos<1||dotpos-apos<2) {
      alert(defaultText);
      return false;
    }
    else {
      return true;
    }
  }
  return true;
}

function validate_content(field, defaultText) {
  with (field) {
    if(value.length < 5) {
      alert("评论不能少于五字！");
      return false;
    }
    else if(value.length > 65535) {
      alert("评论太长！");
      return false;
    }
  }
  return true;
}

function validate_form(form) {
  with (form) {
    if (validate_name(form["comment[commenter]"], "不是一个有效的昵称！") == false) {
      form["comment[commenter]"].focus();
      return false
    }

    var email = this["comment[email]"];
    if (validate_email(email, "不是一个有效的电子邮件地址！") == false) {
      email.focus();
      return false
    }

    var content = this["comment[content]"];
    if (validate_content(content, "不是一个有效的评论!") == false) {
      content.focus();
      return false
    }
  }
  return true;
}
</script>

app/views/layouts/_footer.html.erb
<footer class="footer text-right">
  <nav>
    <ul>
      <li>
        xblog&nbsp;
        <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span>
        &nbsp;2016 - 2016
      </li>
      <br>
      <li>
        Build by <%= link_to "xiaok", 'https://github.com/xuqix/XBlog' %>
        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
      </li>
      <br>
      <li>
        <%= link_to "关于",   '#' %>
        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
      </li>
      <br>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-left navbar-inverse nav-stacked">
  <div class="container">
    <nav class="tab-bar">
      <h3 class="text-center title-nav"><%= link_to "XBLOG", root_path, id: "title-nav" %></h3>
      <ul class="nav navbar-nav navbar-right">
        <section class="left-small">
          <a href="#menu-toggle" class="btn btn-lg" id="menu-toggle">
            <span class="glyphicon glyphicon-list"></span>
          </a>
        </section>
    </ul>
    </nav>
  </div>
</header>

<script>
$(document).ready(function(){});
$("#menu-toggle").click(function(e) {
  e.preventDefault();
  $("#wrapper").toggleClass("toggled");
});

$("a, button").focus(function(){
  this.blur()
});
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Custom CSS -->
  <link href="css/simple-sidebar.css" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div id="wrapper">

    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand"><a href="">XBlog</a></li>
        <li><%= link_to "主页", root_path %></li>
        <li><%= link_to "关于我", '#' %></li>
      </ul>
    </div>

    <!-- content -->
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation error-message">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>